In [9]:
# SQLAlchemy
from sqlalchemy import create_engine

# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base

# Allow us to declare column types
from sqlalchemy import Table, Column, Integer, String, Float, MetaData

#pandas for data manipulation and export
import pandas as pd

In [10]:
db_uri = "sqlite:///db.sqlite"
engine = create_engine(db_uri, echo = True)

In [30]:
df = pd.read_csv("data/S2802.csv", na_values = ["-"])
df = df.astype({"fips_id": "object"})
print(df.dtypes[1:20])
#df.columns
df

fips_id                                                               object
GeographicAreaName                                                    object
tract_name                                                            object
county_name                                                           object
state                                                                 object
E_Households                                                           int64
E_Total_Households_Race_Hispanic_Latino_Whitealone                     int64
E_Computer_Broadband_Totalhouseholds                                   int64
E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone        int64
PE_Computer_Broadband_Household                                      float64
PE_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone     float64
E_Computer_NoInternet_Households                                       int64
E_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone       int64
PE_Computer_NoInternet_Households                                    float64
PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone    float64
E_NoComputer_Households                                                int64
E_NoComputer_Households_Race_Hispanic_Latino_Whitealone                int64
PE_NoComputer_Households                                             float64
PE_NoComputer_Households_Race_Hispanic_Latino_Whitealone             float64
dtype: object

,id,fips_id,GeographicAreaName,tract_name,county_name,state,E_Households,E_Total_Households_Race_Hispanic_Latino_Whitealone,E_Computer_Broadband_Totalhouseholds,E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,...,PE_Computer_NoInternet_Households_EducationHSsomeCollege,E_NoComputer_Households_EducationHSsomeCollege,PE_NoComputer_Households_EducationHSsomeCollege,E_Total_Households_EducationBachelorsPlus,E_Computer_Broadband_Households_EducationBachelorsPlus,PE_Computer_Broadband_Households_EducationBachelorsPlus,E_Computer_NoInternet_Households_EducationBachelorsPlus,PE_Computer_NoInternet_Households_EducationBachelorsPlus,E_NoComputer_Households_EducationBachelorsPlus,PE_NoComputer_Households_EducationBachelorsPlus
0,1400000US41001950100,41001950100,"Census Tract 9501, Baker County, Oregon",Census Tract 9501,Baker,Oregon,2806,2659,2020,1887,...,18.1,122,8.0,449,419,93.3,1,0.2,27,6.0
1,1400000US41001950200,41001950200,"Census Tract 9502, Baker County, Oregon",Census Tract 9502,Baker,Oregon,3435,3247,2764,2685,...,12.4,226,14.6,661,607,91.8,14,2.1,40,6.1
2,1400000US41001950300,41001950300,"Census Tract 9503, Baker County, Oregon",Census Tract 9503,Baker,Oregon,2419,2244,1943,1772,...,11.2,207,18.3,231,224,97.0,0,0.0,7,3.0
3,1400000US41001950400,41001950400,"Census Tract 9504, Baker County, Oregon",Census Tract 9504,Baker,Oregon,2634,2413,2100,1979,...,10.4,197,14.4,493,424,86.0,36,7.3,33,6.7
4,1400000US41001950500,41001950500,"Census Tract 9505, Baker County, Oregon",Census Tract 9505,Baker,Oregon,2166,1982,1751,1567,...,18.9,88,9.2,429,403,93.9,16,3.7,10,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,1400000US41071030702,41071030702,"Census Tract 307.02, Yamhill County, Oregon",Census Tract 307.02,Yamhill,Oregon,7347,6534,6044,5248,...,9.3,253,8.0,1053,936,88.9,69,6.6,48,4.6
830,1400000US41071030801,41071030801,"Census Tract 308.01, Yamhill County, Oregon",Census Tract 308.01,Yamhill,Oregon,5311,4429,4266,3634,...,12.8,326,15.8,557,486,87.3,49,8.8,22,3.9
831,1400000US41071030802,41071030802,"Census Tract 308.02, Yamhill County, Oregon",Census Tract 308.02,Yamhill,Oregon,3914,3008,3199,2309,...,12.7,123,8.3,291,261,89.7,22,7.6,8,2.7
832,1400000US41071030900,41071030900,"Census Tract 309, Yamhill County, Oregon",Census Tract 309,Yamhill,Oregon,4829,4285,4175,3660,...,7.7,59,2.9,731,678,92.7,40,5.5,13,1.8
833,1400000US41071031000,41071031000,"Census Tract 310, Yamhill County, Oregon",Census Tract 310,Yamhill,Oregon,4140,3639,3435,3084,...,8.5,131,6.6,673,589,87.5,69,10.3,15,2.2

In [25]:
df.columns

Index(['id', 'fips_id', 'GeographicAreaName', 'tract_name', 'county_name',
       'state', 'E_Households',
       'E_Total_Households_Race_Hispanic_Latino_Whitealone',
       'E_Computer_Broadband_Totalhouseholds',
       'E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone',
       ...
       'PE_Computer_NoInternet_Households_EducationHSsomeCollege',
       'E_NoComputer_Households_EducationHSsomeCollege',
       'PE_NoComputer_Households_EducationHSsomeCollege',
       'E_Total_Households_EducationBachelorsPlus',
       'E_Computer_Broadband_Households_EducationBachelorsPlus',
       'PE_Computer_Broadband_Households_EducationBachelorsPlus',
       'E_Computer_NoInternet_Households_EducationBachelorsPlus',
       'PE_Computer_NoInternet_Households_EducationBachelorsPlus',
       'E_NoComputer_Households_EducationBachelorsPlus',
       'PE_NoComputer_Households_EducationBachelorsPlus'],
      dtype='object', length=104)

# Join Lat/Lon

In [33]:
latlon = pd.read_csv("data/fips_latlon.csv")
latlon

                   GEO_ID  StateTractCode   Latitude   Longitude
0    1400000US41001950100     41001950100  44.615008 -118.152741
1    1400000US41001950200     41001950200  44.778647 -117.875153
2    1400000US41001950300     41001950300  44.560517 -117.579236
3    1400000US41001950400     41001950400  44.791150 -117.817211
4    1400000US41001950500     41001950500  44.903897 -117.785766
..                    ...             ...        ...         ...
829  1400000US41071030702     41071030702  45.200776 -123.217695
830  1400000US41071030801     41071030801  45.220449 -123.188742
831  1400000US41071030802     41071030802  45.199317 -123.195395
832  1400000US41071030900     41071030900  45.166444 -123.064743
833  1400000US41071031000     41071031000  45.126344 -123.170842

[834 rows x 4 columns]

In [36]:
newdf = df.merge(latlon, how="inner", left_on=["id","fips_id"], right_on=["GEO_ID","StateTractCode"])
newdf

,id,fips_id,GeographicAreaName,tract_name,county_name,state,E_Households,E_Total_Households_Race_Hispanic_Latino_Whitealone,E_Computer_Broadband_Totalhouseholds,E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,...,E_Computer_Broadband_Households_EducationBachelorsPlus,PE_Computer_Broadband_Households_EducationBachelorsPlus,E_Computer_NoInternet_Households_EducationBachelorsPlus,PE_Computer_NoInternet_Households_EducationBachelorsPlus,E_NoComputer_Households_EducationBachelorsPlus,PE_NoComputer_Households_EducationBachelorsPlus,GEO_ID,StateTractCode,Latitude,Longitude
0,1400000US41001950100,41001950100,"Census Tract 9501, Baker County, Oregon",Census Tract 9501,Baker,Oregon,2806,2659,2020,1887,...,419,93.3,1,0.2,27,6.0,1400000US41001950100,41001950100,44.615008,-118.152741
1,1400000US41001950200,41001950200,"Census Tract 9502, Baker County, Oregon",Census Tract 9502,Baker,Oregon,3435,3247,2764,2685,...,607,91.8,14,2.1,40,6.1,1400000US41001950200,41001950200,44.778647,-117.875153
2,1400000US41001950300,41001950300,"Census Tract 9503, Baker County, Oregon",Census Tract 9503,Baker,Oregon,2419,2244,1943,1772,...,224,97.0,0,0.0,7,3.0,1400000US41001950300,41001950300,44.560517,-117.579236
3,1400000US41001950400,41001950400,"Census Tract 9504, Baker County, Oregon",Census Tract 9504,Baker,Oregon,2634,2413,2100,1979,...,424,86.0,36,7.3,33,6.7,1400000US41001950400,41001950400,44.791150,-117.817211
4,1400000US41001950500,41001950500,"Census Tract 9505, Baker County, Oregon",Census Tract 9505,Baker,Oregon,2166,1982,1751,1567,...,403,93.9,16,3.7,10,2.3,1400000US41001950500,41001950500,44.903897,-117.785766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,1400000US41071030702,41071030702,"Census Tract 307.02, Yamhill County, Oregon",Census Tract 307.02,Yamhill,Oregon,7347,6534,6044,5248,...,936,88.9,69,6.6,48,4.6,1400000US41071030702,41071030702,45.200776,-123.217695
830,1400000US41071030801,41071030801,"Census Tract 308.01, Yamhill County, Oregon",Census Tract 308.01,Yamhill,Oregon,5311,4429,4266,3634,...,486,87.3,49,8.8,22,3.9,1400000US41071030801,41071030801,45.220449,-123.188742
831,1400000US41071030802,41071030802,"Census Tract 308.02, Yamhill County, Oregon",Census Tract 308.02,Yamhill,Oregon,3914,3008,3199,2309,...,261,89.7,22,7.6,8,2.7,1400000US41071030802,41071030802,45.199317,-123.195395
832,1400000US41071030900,41071030900,"Census Tract 309, Yamhill County, Oregon",Census Tract 309,Yamhill,Oregon,4829,4285,4175,3660,...,678,92.7,40,5.5,13,1.8,1400000US41071030900,41071030900,45.166444,-123.064743
833,1400000US41071031000,41071031000,"Census Tract 310, Yamhill County, Oregon",Census Tract 310,Yamhill,Oregon,4140,3639,3435,3084,...,589,87.5,69,10.3,15,2.2,1400000US41071031000,41071031000,45.126344,-123.170842

## Join FCC dataframe

In [14]:
fcc = pd.read_csv("data/fcc_data.csv") #, na_values = ["-"]
fcc = fcc.astype({"tract": "object"})
fcc.dtypes
fcc

,Unnamed: 0,logrecno,provider_id,frn,providername,dbaname,holdingcompanyname,hoconum,hocofinal,stateabbr,blockcode,tract,techcode,consumer,maxaddown,maxadup,business,maxcirdown,maxcirup
0,0,4268,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10,1,40,10
1,1,4269,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10,1,40,10
2,2,4270,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10,1,40,10
3,3,4271,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10,1,40,10
4,4,4272,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950400,70,1,40,10,1,40,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,5263,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10,1,40,10
996,996,5264,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10,1,40,10
997,997,5265,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10,1,40,10
998,998,5266,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10,1,40,10
999,999,5267,48582,17678236,Webformix Company,Webformix,Webformix Company,290118,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10,1,40,10

In [43]:
fcc_df = fcc[["dbaname","hocofinal","stateabbr","blockcode", "tract", "techcode","consumer","maxaddown","maxadup"]]
fcc_df

,dbaname,hocofinal,stateabbr,blockcode,tract,techcode,consumer,maxaddown,maxadup
0,Webformix,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10
1,Webformix,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10
2,Webformix,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10
3,Webformix,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10
4,Webformix,Webformix Company,OR,4.101400e+14,41013950400,70,1,40,10
...,...,...,...,...,...,...,...,...,...
995,Webformix,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10
996,Webformix,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10
997,Webformix,Webformix Company,OR,4.101400e+14,41013950300,70,1,40,10
998,Webformix,Webformix Company,OR,4.101400e+14,41013950200,70,1,40,10
999,Webformix,Webformix Company,OR,4.101400e+14,41013950100,70,1,40,10

In [37]:
newdf.to_sql("s2802", con=engine, if_exists="replace", index_label=None)

2020-07-25 12:10:39,880 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("s2802")
2020-07-25 12:10:39,881 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,883 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("s2802")
2020-07-25 12:10:39,885 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,891 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-07-25 12:10:39,893 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,903 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("s2802")
2020-07-25 12:10:39,916 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,939 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 's2802' AND type = 'table'
2020-07-25 12:10:39,943 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,949 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("s2802")
2020-07-25 12:10:39,953 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,960 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("s2802")
2020-07-25 12:10:39,969 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,976 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 's2802' AND type = 'table'
2020-07-25 12:10:39,979 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,988 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("s2802")
2020-07-25 12:10:39,992 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:39,998 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_s2802_index")
2020-07-25 12:10:40,002 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,005 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("s2802")
2020-07-25 12:10:40,012 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,015 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_s2802_index")
2020-07-25 12:10:40,016 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,019 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 's2802' AND type = 'table'
2020-07-25 12:10:40,021 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,038 INFO sqlalchemy.engine.base.Engine
DROP TABLE s2802
2020-07-25 12:10:40,039 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,059 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:10:40,167 INFO sqlalchemy.engine.base.Engine
CREATE TABLE s2802 (
	"index" BIGINT,
	id TEXT,
	fips_id BIGINT,
	"GeographicAreaName" TEXT,
	tract_name TEXT,
	county_name TEXT,
	state TEXT,
	"E_Households" BIGINT,
	"E_Total_Households_Race_Hispanic_Latino_Whitealone" BIGINT,
	"E_Computer_Broadband_Totalhouseholds" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone" BIGINT,
	"PE_Computer_Broadband_Household" FLOAT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone" FLOAT,
	"E_Computer_NoInternet_Households" BIGINT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone" BIGINT,
	"PE_Computer_NoInternet_Households" FLOAT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone" FLOAT,
	"E_NoComputer_Households" BIGINT,
	"E_NoComputer_Households_Race_Hispanic_Latino_Whitealone" BIGINT,
	"PE_NoComputer_Households" FLOAT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_Whitealone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_Asianalone" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_Asianalone" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_Asianalone" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_Asianalone" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Asianalone" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_Asianalone" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_Asianalone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_Someotherracealone" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_Someotherracealone" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_Someotherracealone" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_Someotherracealone" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Someotherracealone" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_Someotherracealone" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_Someotherracealone" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_Twoormoreraces" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_Twoormoreraces" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_Twoormoreraces" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_Twoormoreraces" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Twoormoreraces" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_Twoormoreraces" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_Twoormoreraces" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)" FLOAT,
	"E_Total_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" BIGINT,
	"E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" BIGINT,
	"PE_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" FLOAT,
	"E_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" BIGINT,
	"PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" FLOAT,
	"E_NoComputer_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" BIGINT,
	"PE_NoComputer_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino" FLOAT,
	"E_Total_Households_Education" BIGINT,
	"E_Computer_Broadband_Households_Education" BIGINT,
	"PE_Computer_Broadband_Households_Education" FLOAT,
	"E_Computer_NoInternet_Households_Education" BIGINT,
	"PE_Computer_NoInternet_Households_Education" FLOAT,
	"E_NoComputer_Households_Education" BIGINT,
	"PE_NoComputer_Households_Education" FLOAT,
	"E_Total_Households_EducationNoHS" BIGINT,
	"E_Computer_Broadband_Households_EducationNoHS" BIGINT,
	"PE_Computer_Broadband_Households_EducationNoHS" FLOAT,
	"E_Computer_NoInternet_Households_EducationNoHS" BIGINT,
	"PE_Computer_NoInternet_Households_EducationNoHS" FLOAT,
	"E_NoComputer_Households_EducationNoHS" BIGINT,
	"PE_NoComputer_Households_EducationNoHS" FLOAT,
	"E_Total_Households_EducationHSsomeCollege" BIGINT,
	"E_Computer_Broadband_Households_EducationHSsomeCollege" BIGINT,
	"PE_Computer_Broadband_Households_EducationHSsomeCollege" FLOAT,
	"E_Computer_NoInternet_Households_EducationHSsomeCollege" BIGINT,
	"PE_Computer_NoInternet_Households_EducationHSsomeCollege" FLOAT,
	"E_NoComputer_Households_EducationHSsomeCollege" BIGINT,
	"PE_NoComputer_Households_EducationHSsomeCollege" FLOAT,
	"E_Total_Households_EducationBachelorsPlus" BIGINT,
	"E_Computer_Broadband_Households_EducationBachelorsPlus" BIGINT,
	"PE_Computer_Broadband_Households_EducationBachelorsPlus" FLOAT,
	"E_Computer_NoInternet_Households_EducationBachelorsPlus" BIGINT,
	"PE_Computer_NoInternet_Households_EducationBachelorsPlus" FLOAT,
	"E_NoComputer_Households_EducationBachelorsPlus" BIGINT,
	"PE_NoComputer_Households_EducationBachelorsPlus" FLOAT,
	"GEO_ID" TEXT,
	"StateTractCode" BIGINT,
	"Latitude" FLOAT,
	"Longitude" FLOAT
)

2020-07-25 12:10:40,171 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,184 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:10:40,195 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_s2802_index ON s2802 ("index")
2020-07-25 12:10:40,203 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:10:40,212 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:10:40,242 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-07-25 12:10:40,453 INFO sqlalchemy.engine.base.Engine INSERT INTO s2802 ("index", id, fips_id, "GeographicAreaName", tract_name, county_name, state, "E_Households", "E_Total_Households_Race_Hispanic_Latino_Whitealone", "E_Computer_Broadband_Totalhouseholds", "E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone", "PE_Computer_Broadband_Household", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone", "E_Computer_NoInternet_Households", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone", "PE_Computer_NoInternet_Households", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone", "E_NoComputer_Households", "E_NoComputer_Households_Race_Hispanic_Latino_Whitealone", "PE_NoComputer_Households", "PE_NoComputer_Households_Race_Hispanic_Latino_Whitealone", "E_Total_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "E_Computer_Broadband_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "E_NoComputer_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "PE_NoComputer_Households_Race_Hispanic_Latino_BlackorAfricanAmericanalone", "E_Total_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "E_Computer_Broadband_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "E_NoComputer_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "PE_NoComputer_Households_Race_Hispanic_Latino_AmericanIndianandAlaskaNativealone", "E_Total_Households_Race_Hispanic_Latino_Asianalone", "E_Computer_Broadband_Households_Race_Hispanic_Latino_Asianalone", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_Asianalone", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_Asianalone", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Asianalone", "E_NoComputer_Households_Race_Hispanic_Latino_Asianalone", "PE_NoComputer_Households_Race_Hispanic_Latino_Asianalone", "E_Total_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "E_Computer_Broadband_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "E_NoComputer_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "PE_NoComputer_Households_Race_Hispanic_Latino_NativeHawaiianandOtherPacificIslanderalone", "E_Total_Households_Race_Hispanic_Latino_Someotherracealone", "E_Computer_Broadband_Households_Race_Hispanic_Latino_Someotherracealone", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_Someotherracealone", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_Someotherracealone", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Someotherracealone", "E_NoComputer_Households_Race_Hispanic_Latino_Someotherracealone", "PE_NoComputer_Households_Race_Hispanic_Latino_Someotherracealone", "E_Total_Households_Race_Hispanic_Latino_Twoormoreraces", "E_Computer_Broadband_Households_Race_Hispanic_Latino_Twoormoreraces", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_Twoormoreraces", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_Twoormoreraces", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Twoormoreraces", "E_NoComputer_Households_Race_Hispanic_Latino_Twoormoreraces", "PE_NoComputer_Households_Race_Hispanic_Latino_Twoormoreraces", "E_Total_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "E_Computer_Broadband_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "E_NoComputer_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "PE_NoComputer_Households_Race_Hispanic_Latino_HispanicorLatinoorigin(ofanyrace)", "E_Total_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "E_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "PE_Computer_Broadband_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "E_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "PE_Computer_NoInternet_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "E_NoComputer_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "PE_NoComputer_Households_Race_Hispanic_Latino_Whitealone,notHispanicorLatino", "E_Total_Households_Education", "E_Computer_Broadband_Households_Education", "PE_Computer_Broadband_Households_Education", "E_Computer_NoInternet_Households_Education", "PE_Computer_NoInternet_Households_Education", "E_NoComputer_Households_Education", "PE_NoComputer_Households_Education", "E_Total_Households_EducationNoHS", "E_Computer_Broadband_Households_EducationNoHS", "PE_Computer_Broadband_Households_EducationNoHS", "E_Computer_NoInternet_Households_EducationNoHS", "PE_Computer_NoInternet_Households_EducationNoHS", "E_NoComputer_Households_EducationNoHS", "PE_NoComputer_Households_EducationNoHS", "E_Total_Households_EducationHSsomeCollege", "E_Computer_Broadband_Households_EducationHSsomeCollege", "PE_Computer_Broadband_Households_EducationHSsomeCollege", "E_Computer_NoInternet_Households_EducationHSsomeCollege", "PE_Computer_NoInternet_Households_EducationHSsomeCollege", "E_NoComputer_Households_EducationHSsomeCollege", "PE_NoComputer_Households_EducationHSsomeCollege", "E_Total_Households_EducationBachelorsPlus", "E_Computer_Broadband_Households_EducationBachelorsPlus", "PE_Computer_Broadband_Households_EducationBachelorsPlus", "E_Computer_NoInternet_Households_EducationBachelorsPlus", "PE_Computer_NoInternet_Households_EducationBachelorsPlus", "E_NoComputer_Households_EducationBachelorsPlus", "PE_NoComputer_Households_EducationBachelorsPlus", "GEO_ID", "StateTractCode", "Latitude", "Longitude") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-07-25 12:10:40,454 INFO sqlalchemy.engine.base.Engine ((0, '1400000US41001950100', 41001950100, 'Census Tract 9501, Baker County, Oregon', 'Census Tract 9501', ' Baker', 'Oregon', 2806, 2659, 2020, 1887, 72.0, 71.0, 555, 541, 19.8, 20.3, 199, 199, 7.1, 7.5, 26, 26, 100.0, 0, 0.0, 0, 0.0, 24, 24, 100.0, 0, 0.0, 0, 0.0, 22, 22, 100.0, 0, 0.0, 0, 0.0, 9, 2, 22.2, 7, 77.8, 0, 0.0, 47, 47, 100.0, 0, 0.0, 0, 0.0, 19, 12, 63.2, 7, 36.8, 0, 0.0, 161, 79, 49.1, 82, 50.9, 0, 0.0, 2535, 1843, 72.7, 461, 18.2, 199, 7.9, 2217, 1614, 72.8, 372, 16.8, 199, 9.0, 249, 103, 41.4, 96, 38.6, 50, 20.1, 1519, 1092, 71.9, 275, 18.1, 122, 8.0, 449, 419, 93.3, 1, 0.2, 27, 6.0, '1400000US41001950100', 41001950100, 44.615008200000005, -118.15274140000001), (1, '1400000US41001950200', 41001950200, 'Census Tract 9502, Baker County, Oregon', 'Census Tract 9502', ' Baker', 'Oregon', 3435, 3247, 2764, 2685, 80.5, 82.7, 255, 238, 7.4, 7.3, 416, 324, 12.1, 10.0, 25, 21, 84.0, 4, 16.0, 0, 0.0, 41, 41, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 0, 0, None, 0, None, 0, None, 99, 8, 8.1, 13, 13.1, 78, 78.8, 23, 9, 39.1, 0, 0.0, 14, 60.9, 133, 31, 23.3, 13, 9.8, 89, 66.9, 3210, 2659, 82.8, 238, 7.4, 313, 9.8, 2374, 1800, 75.8, 210, 8.8, 364, 15.3, 164, 62, 37.8, 4, 2.4, 98, 59.8, 1549, 1131, 73.0, 192, 12.4, 226, 14.6, 661, 607, 91.8, 14, 2.1, 40, 6.1, '1400000US41001950200', 41001950200, 44.778647, -117.87515259999998), (2, '1400000US41001950300', 41001950300, 'Census Tract 9503, Baker County, Oregon', 'Census Tract 9503', ' Baker', 'Oregon', 2419, 2244, 1943, 1772, 80.3, 79.0, 188, 188, 7.8, 8.4, 273, 269, 11.3, 12.0, 53, 53, 100.0, 0, 0.0, 0, 0.0, 52, 52, 100.0, 0, 0.0, 0, 0.0, 14, 14, 100.0, 0, 0.0, 0, 0.0, 9, 5, 55.6, 0, 0.0, 4, 44.4, 2, 2, 100.0, 0, 0.0, 0, 0.0, 45, 45, 100.0, 0, 0.0, 0, 0.0, 18, 13, 72.2, 4, 22.2, 1, 5.6, 2229, 1762, 79.0, 184, 8.3, 268, 12.0, 1684, 1227, 72.9, 175, 10.4, 267, 15.9, 319, 218, 68.3, 48, 15.0, 53, 16.6, 1134, 785, 69.2, 127, 11.2, 207, 18.3, 231, 224, 97.0, 0, 0.0, 7, 3.0, '1400000US41001950300', 41001950300, 44.5605166, -117.57923570000001), (3, '1400000US41001950400', 41001950400, 'Census Tract 9504, Baker County, Oregon', 'Census Tract 9504', ' Baker', 'Oregon', 2634, 2413, 2100, 1979, 79.7, 82.0, 244, 180, 9.3, 7.5, 280, 244, 10.6, 10.1, 0, 0, None, 0, None, 0, None, 0, 0, None, 0, None, 0, None, 50, 50, 100.0, 0, 0.0, 0, 0.0, 25, 0, 0.0, 25, 100.0, 0, 0.0, 72, 7, 9.7, 39, 54.2, 26, 36.1, 74, 64, 86.5, 0, 0.0, 10, 13.5, 92, 27, 29.3, 39, 42.4, 26, 28.3, 2401, 1967, 81.9, 180, 7.5, 244, 10.2, 1995, 1506, 75.5, 199, 10.0, 280, 14.0, 133, 62, 46.6, 21, 15.8, 50, 37.6, 1369, 1020, 74.5, 142, 10.4, 197, 14.4, 493, 424, 86.0, 36, 7.3, 33, 6.7, '1400000US41001950400', 41001950400, 44.79115, -117.8172115), (4, '1400000US41001950500', 41001950500, 'Census Tract 9505, Baker County, Oregon', 'Census Tract 9505', ' Baker', 'Oregon', 2166, 1982, 1751, 1567, 80.8, 79.1, 239, 239, 11.0, 12.1, 176, 176, 8.1, 8.9, 0, 0, None, 0, None, 0, None, 48, 48, 100.0, 0, 0.0, 0, 0.0, 39, 39, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 75, 75, 100.0, 0, 0.0, 0, 0.0, 22, 22, 100.0, 0, 0.0, 0, 0.0, 149, 135, 90.6, 0, 0.0, 14, 9.4, 1911, 1510, 79.0, 239, 12.5, 162, 8.5, 1578, 1193, 75.6, 219, 13.9, 166, 10.5, 189, 99, 52.4, 22, 11.6, 68, 36.0, 960, 691, 72.0, 181, 18.9, 88, 9.2, 429, 403, 93.9, 16, 3.7, 10, 2.3, '1400000US41001950500', 41001950500, 44.9038966, -117.78576629999999), (5, '1400000US41001950600', 41001950600, 'Census Tract 9506, Baker County, Oregon', 'Census Tract 9506', ' Baker', 'Oregon', 1949, 1852, 1521, 1441, 78.0, 77.8, 254, 237, 13.0, 12.8, 167, 167, 8.6, 9.0, 6, 6, 100.0, 0, 0.0, 0, 0.0, 27, 27, 100.0, 0, 0.0, 0, 0.0, 14, 14, 100.0, 0, 0.0, 0, 0.0, 2, 2, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 48, 31, 64.6, 17, 35.4, 0, 0.0, 63, 63, 100.0, 0, 0.0, 0, 0.0, 1789, 1378, 77.0, 237, 13.2, 167, 9.3, 1593, 1221, 76.6, 198, 12.4, 167, 10.5, 123, 64, 52.0, 38, 30.9, 21, 17.1, 1112, 833, 74.9, 134, 12.1, 138, 12.4, 358, 324, 90.5, 26, 7.3, 8, 2.2, '1400000US41001950600', 41001950600, 44.851074, -117.2473647), (6, '1400000US41003000100', 41003000100, 'Census Tract 1, Benton County, Oregon', 'Census Tract 1', ' Benton', 'Oregon', 7999, 7195, 7593, 6789, 94.9, 94.4, 299, 299, 3.7, 4.2, 94, 94, 1.2, 1.3, 79, 79, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 318, 318, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 198, 198, 100.0, 0, 0.0, 0, 0.0, 209, 209, 100.0, 0, 0.0, 0, 0.0, 932, 932, 100.0, 0, 0.0, 0, 0.0, 6460, 6054, 93.7, 299, 4.6, 94, 1.5, 5471, 5219, 95.4, 145, 2.7, 94, 1.7, 378, 364, 96.3, 0, 0.0, 14, 3.7, 2329, 2151, 92.4, 137, 5.9, 41, 1.8, 2764, 2704, 97.8, 8, 0.3, 39, 1.4, '1400000US41003000100', 41003000100, 44.535963, -123.2632065), (7, '1400000US41003000202', 41003000202, 'Census Tract 2.02, Benton County, Oregon', 'Census Tract 2.02', ' Benton', 'Oregon', 5104, 4152, 4849, 3943, 95.0, 95.0, 113, 113, 2.2, 2.7, 142, 96, 2.8, 2.3, 169, 169, 100.0, 0, 0.0, 0, 0.0, 20, 20, 100.0, 0, 0.0, 0, 0.0, 447, 401, 89.7, 0, 0.0, 46, 10.3, 9, 9, 100.0, 0, 0.0, 0, 0.0, 63, 63, 100.0, 0, 0.0, 0, 0.0, 244, 244, 100.0, 0, 0.0, 0, 0.0, 145, 145, 100.0, 0, 0.0, 0, 0.0, 4085, 3876, 94.9, 113, 2.8, 96, 2.4, 3630, 3397, 93.6, 113, 3.1, 120, 3.3, 50, 17, 34.0, 0, 0.0, 33, 66.0, 1133, 989, 87.3, 113, 10.0, 31, 2.7, 2447, 2391, 97.7, 0, 0.0, 56, 2.3, '1400000US41003000202', 41003000202, 44.5379586, -123.3077291)  ... displaying 10 of 834 total bound parameter sets ...  (832, '1400000US41071030900', 41071030900, 'Census Tract 309, Yamhill County, Oregon', 'Census Tract 309', ' Yamhill', 'Oregon', 4829, 4285, 4175, 3660, 86.5, 85.4, 446, 417, 9.2, 9.7, 200, 200, 4.1, 4.7, 13, 13, 100.0, 0, 0.0, 0, 0.0, 35, 35, 100.0, 0, 0.0, 0, 0.0, 18, 10, 55.6, 8, 44.4, 0, 0.0, 0, 0, None, 0, None, 0, None, 255, 234, 91.8, 21, 8.2, 0, 0.0, 223, 223, 100.0, 0, 0.0, 0, 0.0, 1123, 828, 73.7, 139, 12.4, 156, 13.9, 3492, 3141, 89.9, 299, 8.6, 44, 1.3, 3177, 2728, 85.9, 272, 8.6, 169, 5.3, 423, 250, 59.1, 76, 18.0, 97, 22.9, 2023, 1800, 89.0, 156, 7.7, 59, 2.9, 731, 678, 92.7, 40, 5.5, 13, 1.8, '1400000US41071030900', 41071030900, 45.1664441, -123.06474320000001), (833, '1400000US41071031000', 41071031000, 'Census Tract 310, Yamhill County, Oregon', 'Census Tract 310', ' Yamhill', 'Oregon', 4140, 3639, 3435, 3084, 83.0, 84.7, 434, 326, 10.5, 9.0, 193, 193, 4.7, 5.3, 6, 6, 100.0, 0, 0.0, 0, 0.0, 76, 34, 44.7, 0, 0.0, 0, 0.0, 50, 50, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 60, 60, 100.0, 0, 0.0, 0, 0.0, 309, 201, 65.0, 108, 35.0, 0, 0.0, 326, 203, 62.3, 118, 36.2, 5, 1.5, 3536, 3013, 85.2, 299, 8.5, 188, 5.3, 2857, 2366, 82.8, 277, 9.7, 162, 5.7, 209, 153, 73.2, 40, 19.1, 16, 7.7, 1975, 1624, 82.2, 168, 8.5, 131, 6.6, 673, 589, 87.5, 69, 10.3, 15, 2.2, '1400000US41071031000', 41071031000, 45.1263436, -123.17084229999999))

2020-07-25 12:10:40,499 INFO sqlalchemy.engine.base.Engine COMMIT

In [39]:
engine.execute("SELECT * FROM s2802 LIMIT 2").fetchall()

2020-07-25 12:10:55,737 INFO sqlalchemy.engine.base.Engine SELECT * FROM s2802 LIMIT 2
2020-07-25 12:10:55,741 INFO sqlalchemy.engine.base.Engine ()

[(0, '1400000US41001950100', 41001950100, 'Census Tract 9501, Baker County, Oregon', 'Census Tract 9501', ' Baker', 'Oregon', 2806, 2659, 2020, 1887, 72.0, 71.0, 555, 541, 19.8, 20.3, 199, 199, 7.1, 7.5, 26, 26, 100.0, 0, 0.0, 0, 0.0, 24, 24, 100.0, 0, 0.0, 0, 0.0, 22, 22, 100.0, 0, 0.0, 0, 0.0, 9, 2, 22.2, 7, 77.8, 0, 0.0, 47, 47, 100.0, 0, 0.0, 0, 0.0, 19, 12, 63.2, 7, 36.8, 0, 0.0, 161, 79, 49.1, 82, 50.9, 0, 0.0, 2535, 1843, 72.7, 461, 18.2, 199, 7.9, 2217, 1614, 72.8, 372, 16.8, 199, 9.0, 249, 103, 41.4, 96, 38.6, 50, 20.1, 1519, 1092, 71.9, 275, 18.1, 122, 8.0, 449, 419, 93.3, 1, 0.2, 27, 6.0, '1400000US41001950100', 41001950100, 44.615008200000005, -118.15274140000001),
 (1, '1400000US41001950200', 41001950200, 'Census Tract 9502, Baker County, Oregon', 'Census Tract 9502', ' Baker', 'Oregon', 3435, 3247, 2764, 2685, 80.5, 82.7, 255, 238, 7.4, 7.3, 416, 324, 12.1, 10.0, 25, 21, 84.0, 4, 16.0, 0, 0.0, 41, 41, 100.0, 0, 0.0, 0, 0.0, 0, 0, None, 0, None, 0, None, 0, 0, None, 0, None, 0, None, 99, 8, 8.1, 13, 13.1, 78, 78.8, 23, 9, 39.1, 0, 0.0, 14, 60.9, 133, 31, 23.3, 13, 9.8, 89, 66.9, 3210, 2659, 82.8, 238, 7.4, 313, 9.8, 2374, 1800, 75.8, 210, 8.8, 364, 15.3, 164, 62, 37.8, 4, 2.4, 98, 59.8, 1549, 1131, 73.0, 192, 12.4, 226, 14.6, 661, 607, 91.8, 14, 2.1, 40, 6.1, '1400000US41001950200', 41001950200, 44.778647, -117.87515259999998)]

In [44]:
fcc_df.to_sql("fcc", con=engine, if_exists="replace", index_label=None)

2020-07-25 12:24:07,294 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("fcc")
2020-07-25 12:24:07,299 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,308 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("fcc")
2020-07-25 12:24:07,312 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,316 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-07-25 12:24:07,318 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,322 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("fcc")
2020-07-25 12:24:07,327 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,334 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'fcc' AND type = 'table'
2020-07-25 12:24:07,339 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,350 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("fcc")
2020-07-25 12:24:07,358 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,363 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("fcc")
2020-07-25 12:24:07,366 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,374 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'fcc' AND type = 'table'
2020-07-25 12:24:07,376 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,386 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("fcc")
2020-07-25 12:24:07,390 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,392 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_fcc_index")
2020-07-25 12:24:07,393 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,395 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("fcc")
2020-07-25 12:24:07,396 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,399 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_fcc_index")
2020-07-25 12:24:07,400 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,405 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'fcc' AND type = 'table'
2020-07-25 12:24:07,409 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,412 INFO sqlalchemy.engine.base.Engine
DROP TABLE fcc
2020-07-25 12:24:07,413 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,420 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:24:07,426 INFO sqlalchemy.engine.base.Engine
CREATE TABLE fcc (
	"index" BIGINT,
	dbaname TEXT,
	hocofinal TEXT,
	stateabbr TEXT,
	blockcode FLOAT,
	tract BIGINT,
	techcode BIGINT,
	consumer BIGINT,
	maxaddown BIGINT,
	maxadup BIGINT
)


2020-07-25 12:24:07,427 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,431 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:24:07,432 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_fcc_index ON fcc ("index")
2020-07-25 12:24:07,433 INFO sqlalchemy.engine.base.Engine ()
2020-07-25 12:24:07,437 INFO sqlalchemy.engine.base.Engine COMMIT
2020-07-25 12:24:07,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-07-25 12:24:07,481 INFO sqlalchemy.engine.base.Engine INSERT INTO fcc ("index", dbaname, hocofinal, stateabbr, blockcode, tract, techcode, consumer, maxaddown, maxadup) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-07-25 12:24:07,484 INFO sqlalchemy.engine.base.Engine ((0, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950100, 70, 1, 40, 10), (1, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950300, 70, 1, 40, 10), (2, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950200, 70, 1, 40, 10), (3, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950100, 70, 1, 40, 10), (4, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950400, 70, 1, 40, 10), (5, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950200, 70, 1, 40, 10), (6, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950200, 70, 1, 40, 10), (7, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950100, 70, 1, 40, 10)  ... displaying 10 of 1000 total bound parameter sets ...  (998, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950200, 70, 1, 40, 10), (999, 'Webformix', 'Webformix Company', 'OR', 410140000000000.0, 41013950100, 70, 1, 40, 10))
2020-07-25 12:24:07,492 INFO sqlalchemy.engine.base.Engine COMMIT